import Link from "next/link";
import Head from "next/head";
import Swiper from 'swiper';
import 'swiper/css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Geek Set Web </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/tab-icon.png" />
      </Head>

      {/* Main Nav-Bar */}

    
      <nav className="navbar navbar-expand-lg bg-body-tertiary mainhead ">
  <div className="container">
  <div className="col-lg-4">
  <Link href={'/'}><img className='logo' src="tab-icon.png" alt="Logo" /></Link> 
  </div>
    {/* <a className="navbar-brand" href="#"></a> */}
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarSupportedContent">
      <ul className="navbar-nav me-auto mb-2 mb-lg-0 allnav">
        <li className="nav-item">
          <a className="nav-link active nav-menu" aria-current="page" href="#">Home</a>
        </li>
        <li className="nav-item">
          <a className="nav-link active nav-menu" aria-current="page" href="#about">About</a>
        </li>
        <li className="nav-item">
          <a className="nav-link active nav-menu" aria-current="page" href="#courses">Courses</a>
        </li>
        <li className="nav-item">
          <a className="nav-link active nav-menu" aria-current="page" href="#contact">Contact Us</a>
        </li>
      </ul>
      <form className="d-flex" role="search">
      <a className="button-87" href="#"> Sign In </a>
      </form>
    </div>
  </div>
</nav>



{/* Home Section  */}

<div className="home-body" id="home">
<div className="container">
<div className="row">


<div className="col-lg-6 hero-text">
<br/>

<h1>Ready to take your career to new heights with our immersive Full Stack Development Professional Program.</h1>
<p>Our program is designed to equip you with the skills and expertise needed to thrive in today's fast-paced tech industry.</p>

<br/>
<br/>
<div>

<a className="home-btn" href="#courses" >  Explore the courses </a>
</div>
</div>

<div className="col-lg-6">
<img className="Hero-img" href="#" src="hero-img.svg"/>
</div>

</div>
</div>
</div>

{/* About Section  */}



<div className="About-body" id="about">
<div className="container">
<div className="row">


<div className="col-lg-6 hero-img">
<img className='about-img' src="about-img.jpg" alt="Image"  />


</div>

<div className="col-lg-6 ">
<div className="about-text" >
<h3>About the Courses <iconify-icon icon="material-symbols:bolt-outline"></iconify-icon></h3>
<p> 
Our program is designed to equip you with the skills and expertise needed to thrive in today's fast-paced tech industry. From mastering front-end technologies like HTML, CSS, and JavaScript to diving into back-end frameworks such as Node.js and MongoDB, you'll receive comprehensive training from industry-leading experts.

But the learning doesn't stop there. Upon successful completion of the program, you'll have the opportunity to join our organization as an intern, where you'll work on live projects and gain hands-on experience under the guidance of seasoned professionals. This invaluable experience will not only enhance your skill set but also provide you with insights into industry practices and workflows.

believe in nurturing talent and providing opportunities for growth. Our internship program is designed to help you apply what you've learned in a real-world setting, build your portfolio, and kickstart your career in full stack development.</p>
</div>
</div>

</div>
</div>
</div>


{/*  Coding Technologies  we use section for header   */}

<div className='container'>
<div className='industehead'>
<div className='indhrdesign'>
<span><iconify-icon icon="material-symbols:blur-on" id='indheadicon'></iconify-icon></span>
<h1 className='indheadtext' >Explore & Learn the Emerging Technologies</h1>
<span><iconify-icon icon="material-symbols:blur-on"  id='indheadicon'></iconify-icon></span>
</div>
<p className='indparatext'> We provide best quality Web Development courses  .</p>
</div>
</div>

{/* card section code start here  */}

<div className='container'>
<div className='cardcontainerindus'>


<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="html.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Html</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="css.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>CSS</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="js.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Java Script</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="react.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>React</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="vue js.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Vue Js</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="python.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Python</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="node-js.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Node JS</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="java.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>JAVA</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="git.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Git & GitHub</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="docker.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Docker</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="typescript.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Type Script </p>
</div>
</div>

{/* <div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="postman-icon.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Postman</p>
</div>
</div> */}

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="bootstrap.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>Bootstrap</p>
</div>
</div>
{/* 
<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="graphql-icon.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>GraphQL</p>
</div>
</div>

<div className='industriescard'>
<div className='cardind'>
 <img className="technologies-icons" src="aws-icon.png" alt="Html" />
</div>
<div className='indtext'>
  <p className='indtext2'>AWS</p>
</div>
</div>  */}

</div>
</div>




{/* Courses section  */}


<div className="container">
  <div className="row">
  <div className="course-header-section">
    <div className="col-lg-12">
    <h2 className="course-header"> Web Development training courses </h2>
    
    </div>
    </div>
  </div>
</div>

<div className="container"  id="courses">
  <div className="row">
    <div className="col-lg-12">
      <div className="pre-info-text"> 
    <h2> Pre-requisites </h2>
    <p>To best understand the Full Stack Development Program, it is recommended that you begin with these courses</p>
    <p> Hands on any Programming Language | Basic Of HTML, CSS | Concept Of Object Oriented programming </p> <br />
    <p className="italic-text">*Note : We recommend these prerequisites, but in case of any non fulfilment of prerequisites we adhere to
fundamentals and proceed towards our curriculum*</p>
</div>
    </div>
  </div>
</div>


{/* ------=====( Courses  CARD  section )======------ */}

<div className="course-section-body">
<br />
<div className='container'>
<div className='servicebg'>
<div className='innerdigi'>
<div className='row'>


<div className='col-lg-4'>
<div className='cardnamediv shadow-lg'>
<div className='cardcontainer'>
<div className='cardimg'>
  <img className='cardimage' src="git.jpg" alt="image" />
</div>
<div className='cardcontent'>
  <h3>Module 00 - Course Overview</h3>
  <div className="mod0-container">
  <p> <iconify-icon   icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon>  Course Overview <br/>
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon>  Understanding Agile Methodologies <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon>  Git & Github Introduction

  </p>
  </div>
</div>
</div>
</div>
</div>

<div className='col-lg-4'>
<div className='cardnamediv shadow-lg'>
<div className='cardcontainer'>
<div className='cardimg'>
  <img className='cardimage' src="frontend.jpg" alt="image" />
</div>
<div className='cardcontent'>
  <h3>Module 01 - Frontend <br/> Development</h3>
  <div className="card-para-scroll">
  <p> <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Introduction to Web Technologies <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> HTML5 , CSS3 , Bootstrap <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Introduction to Mind Mapping Tool - Figma <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Geeks Frontend Project 1 <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Introduction To Vanilla Javascript <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Understanding Arrays, Object and Functions   <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> DOM Document Object Model <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Event Listeners And Interaction in Webpage  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Dynamic Content Loading <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> HTTP Protocol And Ajax <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Frontend Dynamic Board Project 2 <br /> 
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Advanced JavaScript ES6 (ECMAScript)  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Introduction To JS Libraries & FrameWorks  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Setting Up Node Package Manager <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Project Architecture  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Angular Directives, Router, HTTP Client  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> E-commerce Frontend App Master  <span className="inner-pera-text">  Project  </span> 
  </p>
  </div>

</div>
</div>
</div>
</div>

<div className='col-lg-4'>
<div className='cardnamediv shadow-lg'>
<div className='cardcontainer'>
<div className='cardimg'>
  <img className='cardimage' src="backend.jpg" alt="image" />
</div>
<div className='cardcontent'>
  <h3> Module 02 - Backend <br /> Development </h3>
  <div className="card-para-scroll">
  <p> 
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon>  Introduction To Server Side Languages   <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon>  Installation Of Nodejs <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Creating Local Server <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> NPM scripts and Package.Json <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Understanding Node Core Module <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Using Third Party Node Modules <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Event Loops <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Routing Request And Http Response <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Parsing Request Bodies <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Node Debugger <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Working With Express Middleware <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> User Interface Templatings Engines EJS <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Converting Static App To Node Driven App  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> MVC Architecture (Model View Controller)  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Express Routers And Refactoring Code  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Dynamic Routes And Request Params  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> File Systems In Node  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Backend E-commerce App Master Project
  </p>
  </div>
</div>
</div>
</div>
</div>

<div className='col-lg-4'>
<div className='cardnamediv shadow-lg'>
<div className='cardcontainer'>
<div className='cardimg'>
  <img className='cardimage' src="database.jpg" alt="image" />
</div>
<div className='cardcontent'>
  <h3> Module 03 - Databases </h3>
  <div className="card-para-scroll-database">
  <p> 
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Introduction To DBMS <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon>  MySql Databases DDL, DML <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon>  Database Connection With Node <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Introduction To NoSql / MongoDB  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Working With Collection   <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Setting Up Mongoose With Node  <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Creating Product Schema  <br /> 
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> CRUD Operations On Database Using Node  <br />
      
  </p>
  </div>
</div>
</div>
</div>
</div>




<div className='col-lg-4'>
<div className='cardnamediv shadow-lg'>
<div className='cardcontainer'>
<div className='cardimg'>
  <img className='cardimage' src="industrial.jpg" alt="image" />
</div>
<div className='cardcontent'>
  <h3> Module 04 - Industries Use <br /> Cases </h3>
  <div className="card-para-scroll">
  <p> 
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Session Cookies <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Adding Authentication <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Sending Emails , OTP <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Advanced Authentication <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Server Side Validation <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Adding Pagination <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Working And Uploading Image File, Zip   <span     className="inner-pera-text"> Files To Databases </span> 
 <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Payment Integration <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Working With RESTful APIs <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> POSTMAN <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Communication Between Servers <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> WebSockets <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Integrating The Angular Application With   <span className="inner-pera-text"> Node Single Backend   </span> <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Geeks All Services E-commerce App    <span className="inner-pera-text"> Master Project   </span>  <br /> 

  </p>
  </div>
</div>
</div>
</div>
</div>



<div className='col-lg-4'>
<div className='cardnamediv shadow-lg'>
<div className='cardcontainer'>
<div className='cardimg'>
  <img className='cardimage' src="Devops.jpg" alt="image" />
</div>
<div className='cardcontent'>
  <h3> Module 05 - Deployment And DevOps </h3>
  <div className="card-para-scroll-devops">
  <p>
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Introduction To AWS, Digital Ocean, Heroku <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Deployment Of Backend On Cloud <br />
  <iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Docker Tool <br />
<iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> Deployment Of Angular App <br />
<iconify-icon icon="material-symbols:arrow-forward-ios-rounded" id="course-icon"></iconify-icon> DevOps Tools <br />
  </p>
  </div>
  
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>




{/*  Course Information  Section  */}

{/* Benefit of Classes Header*/ }

<div className="container">
  <div className="row">
    <div className="col-lg-12">
    <h2 className="benefit-sec-header"> Benefits of our classes </h2>
    </div>
  </div>
</div>


{/*  Benefits lists 1 */}

<div className="container">
<div className="row">
<div className="col-lg-6">
<div className="benefit-list">


<div className="list-icon">
<iconify-icon icon="mdi:video-user" id='benefit-icon'></iconify-icon>
<h3> 110+ hours of Instructor Led Training 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="material-symbols:laptop-windows-outline-rounded" id='benefit-icon'></iconify-icon>
<h3> Online live virtual classroom 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="ic:outline-ondemand-video" id='benefit-icon'></iconify-icon>
<h3>  1 Year Free Doubt Resolving Access 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:industrial" id='benefit-icon'></iconify-icon>
 <h3> 3 industry-based course-end projects 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:server" id='benefit-icon'></iconify-icon> 
  <h3> 1 Year Free Server Space And Domain Name 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:learn-outline" id='benefit-icon'></iconify-icon>
<h3> Interactive learning with Web Frameworks 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:google-classroom" id='benefit-icon'></iconify-icon> 
  <h3> Training centers classroom traditional, one to one mentorship 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:console" id='benefit-icon'></iconify-icon>  
  <h3> Hacks to solve the real time problems 
</h3>
</div>
</div>
</div>

{/* Benefits Lists 2 section */}

<div className="col-lg-6">
<div className="benefit-list">
<div className="list-icon">
<iconify-icon icon="mdi:account-online-outline" id='benefit-icon'></iconify-icon>
<h3 >  Interactions with top notch MNCs Leaders </h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:account-edit-outline" id='benefit-icon'></iconify-icon>
  <h3> Internships and Career Consultancy
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:code-block-braces" id='benefit-icon'></iconify-icon> 
  <h3> Master software programming concepts and implement 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:compressed-file-outline" id='benefit-icon'></iconify-icon>
  <h3> Practitioner with the ability to complete industry projects 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:code-braces" id='benefit-icon'></iconify-icon>
  <h3>  Build an end-to-end application from scratch and test it 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:code-tags-check" id='benefit-icon'></iconify-icon> 
  <h3> Test and deploy features seamlessly to production  
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:code-json" id='benefit-icon'></iconify-icon>
  <h3>  Build a running, industry-aligned project from scratch 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:angularjs" id='benefit-icon'></iconify-icon>
  <h3>  Mastery in Angular, React, Node, Databases
</h3>
</div>
</div>
</div>
</div>
</div>


<div className="list-btn">
<a className="home-btn" href="#courses" >  Explore the courses </a>
</div>


{/*  Targeted Audience section */}

<div className="container">
  <div className="row">
    <div className="col-lg-12">
      <div className="target-text"> 
    <h2> Certification Criteria & Target Audience  : </h2>
    <p> 85 percent of course completion is mandatory
 A score of at least 75 percent in course-end assessment Successful evaluation in at
least one project. </p> <br />
    <p>
  Any UG and PG Students willing to work with web and get industry exposure
 Software and IT professionals interested to up-skill in domain of Frontend, Backend ,DevOps And Databases
 Anyone with a genuine interest in Digital Start Ups and How Web Works And What Can We Explore. </p>
    <br />
</div>
    </div>
  </div>
</div>


{/*  Contact Us Page  Section */}


<div className="contact-body" id="contact">
<div className="container">
  <div className="row">
  <div className="col-lg-12">
  <div>

  <h2 className=" contact-header" > Contact Us for more information </h2>

  </div>
  </div>
  </div>
</div>


  <div className="container">
    <div className="row">
      <div className="col-lg-7"> 
      <div className="left-container">
      <input
                type="hidden"
                name="subject"
                value="you got a new massage"
              />
              <input type="hidden" name="form-name" value="contact" />
              <div className="mb-3">
                <label
                  for="exampleFormControlInput1"
                  className="form-label inputhead"
                >
                  Name :
                </label>
                <input
                  type="text"
                  name="name"
                  className="form-control"
                  id="exampleFormControlInput1"
                  placeholder=" Full Name"
                  required
                />
              </div>

              <div className="mb-3">
                <label
                  for="exampleFormControlInput1"
                  className="form-label inputhead"
                >
                  Phone no :
                </label>
                <input
                  type="number"
                  name="mobile"
                  className="form-control"
                  id="exampleFormControlInput2"
                  placeholder=" Phone No with country code"
                  required
                />
              </div>

              <div className="mb-3">
                <label
                  for="exampleFormControlInput1"
                  className="form-label inputhead"
                >
                  E-mail :
                </label>
                <input
                  type="email"
                  name="email"
                  className="form-control"
                  id="exampleFormControlInput1"
                  placeholder="Learncode@gmail.com"
                  required
                />
              </div>

              <div className="mb-3">
                <label
                  for="exampleFormControlInput1"
                  className="form-label inputhead"
                >
                  Subject :
                </label>
                <input
                  type="text"
                  name="mysubject"
                  className="form-control"
                  id="exampleFormControlInput1"
                  placeholder="Your Query"
                  required
                />
              </div>

              <div className="mb-3">
                <label
                  for="exampleFormControlTextarea1"
                  className="form-label inputhead"
                >
                  Message :
                </label>
                <textarea
                  className="form-control"
                  type="text"
                  name="massage"
                  id="exampleFormControlTextarea1"
                  rows="3"
                  placeholder="Your message"
                  required
                ></textarea>
              </div>
              <br />
              <br />

              <button type="submit" className="home-btn" role="button">   Submit    </button>  
              <br />  
                </div>
    </div>
      <div className="col-lg-5">
      <div className="right-container">
      <h2 className="container-head">Contact Us</h2>
          
      <div className="list-icon">
      <iconify-icon icon="mdi:location-radius" id='contact-icon'></iconify-icon>
  <h3 className="right-text"> Address : 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:phone" id='contact-icon'></iconify-icon>
  <h3 className="right-text" > Phone No : 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:email-outline" id='contact-icon'></iconify-icon>
  <h3 className="right-text"> Email-Id : 
</h3>
</div>

<div className="list-icon">
<iconify-icon icon="mdi:question-mark" id='contact-icon'></iconify-icon>
 <h3 className="right-text"> You have any queries ? Contact Us</h3>
</div>

<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti consectetur quidem voluptatum, a quia obcaecati? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit, iure.</p>

      </div>

      </div>
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    </div>
  </div>



  {/* ----------------- Blog section --------------------- */}

<div className="container">
  <div className="row">
    <div className="col-lg-12">
      <div className="blog-header">
        <p> Recent Blog-posts & Newsletter </p>
        <h2> Blogs & Newsletter </h2>
      </div>
    </div>
  </div>
</div>



<div className='container blog-body'>
<div className="row">
<div className="col-lg-4">
<div className='cardcontainer-indus'>

<a href="#">
<div className='industriescard'>
<div className='cardind'>
 <img className="blog-icon" src="web-dev.svg" alt="Html" />
</div>
<div className='ind-text'>
  <h2> About Software DevelopmentIndustry </h2>
  <p> The global software engineering market is expected to grow to approximately USD $37.4
billion by 2022, at a CAGR of nearly 12 percent.</p>
<p className="date-text">  Date : 07-May-2024 </p>
</div>
</div>
</a>
</div>
</div>


<div className="col-lg-4">
<div className='cardcontainer-indus'>
<a href="#">
<div className='industriescard'>
<div className='cardind'>
 <img className="blog-icon" src="backend-tech.svg" alt="Html" />
</div>
<div className='ind-text'>
  <h2> Backend-Development </h2>
  <p> The global software engineering market is expected to grow to approximately USD $37.4
billion by 2022, at a CAGR of nearly 12 percent.lorem10  adipisicing elit. Ut, nesciunt?.</p>
<p className="date-text"> Date : 07-May-2024 </p>
</div>
</div>
</a>
</div>
</div>


<div className="col-lg-4">
<div className='cardcontainer-indus'>
<a href="#">
<div className='industriescard'>
<div className='cardind'>
 <img className="blog-icon" src="front-end.svg" alt="Html" />
</div>
<div className='ind-text'>
  <h2> Frontend-Development  </h2>
  <p> The global software engineering market is expected to grow to approximately USD $37.4
billion by 2022, at a CAGR of nearly 12 percent.lorem10  adipisicing elit. Ut, nesciunt?</p>
<p className="date-text"> Date : 07-May-2024 </p>
</div>
</div>
</a>
</div>
</div>
</div>
</div>





{/*  Footer section  */}

<div className="footer-section">
  <div className="container">
    <div className="row">
      <div className="col-lg-4 col-sm-4">
      <div className="first-colum">

      <h2>Geek <span className="footer-tex-word"> Set Web </span> </h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti, nihil dolorem cupiditate esse lorm6 Lorem ipsum dolor sit amet consectetur.laboriosam vero.</p>

     
      <div className="f-icon">
     <a href="#"> <iconify-icon icon="ic:outline-facebook" id="footer-icon"></iconify-icon></a>
     <a href="#"> <iconify-icon icon="mdi:instagram" id="footer-icon"></iconify-icon></a>
     <a href="#"> <iconify-icon icon="mdi:twitter" id="footer-icon"></iconify-icon></a> 
     <a href="#"> <iconify-icon icon="mdi:youtube" id="footer-icon"></iconify-icon></a>

      </div>
      </div>
      </div>
      
      <div className="col-lg-8 col-sm-8">
     <div  className="footer-heading"> 
      <h2> Lorem ipsum dolor, sit amet consectetur adipisicing elit.. </h2>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non repellat deleniti eos. Lorem ipsum dolor sit amet. </p>
      </div>
      </div>


    </div>
  </div>
</div>

<div className="footer-end-section">
  <div className="container">
    <div className="row">
      <div className=" col-lg-12">
      <h2> © Copyright 2024 - Geek Set Web All Rights Reserved. </h2>
      </div>
      </div>
      </div>
      </div>




    </>
  );
}
